Feature #r115 add pagination for super admin page (main and universityList)
ita-social-projects/YIF_Frontend pull request #169
Opened 2021-06-03 11:36 UTC by ostannja

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-06-09 09:33 UTC, TionCada requested changes
A lot of work has been done in this task so far. I would like to highlight that pagination was taken out in separate component, which is very good. But I have some advices which are worth paying attention to before merging the branch with dev:

1) If I'm right, these styles should not be applied in superAdminAccount component (src/components/superAdmin/superAdminAccount/superAdminAccount.module.scss), as they're already applied in the pagination component (src/components/pagination/pagination.module.scss) and they have no effect on layout.

2)  If I'm right, these styles should not be applied in universityListPage component (src/pages/superAdminPages/universityListPage/universityListPage.module.scss), as they're already applied in the pagination component (src/components/pagination/pagination.module.scss) and they have no effect on layout.

3) Please, make the container a little bit smaller on these two pages, so it don't occupy the full width of page. Also, add margin or padding right under the pagination component on both pages. 
1.
![1](https://user-images.githubusercontent.com/71350925/121328765-4a236400-c91d-11eb-9807-74e439625d64.png)
2.
![2](https://user-images.githubusercontent.com/71350925/121328768-4abbfa80-c91d-11eb-9bdb-51897798caf9.png)

2021-06-10 09:18 UTC, ostannja commented
> A lot of work has been done in this task so far. I would like to highlight that pagination was taken out in separate component, which is very good. But I have some advices which are worth paying attention to before merging the branch with dev:
> 
> 1. If I'm right, these styles should not be applied in superAdminAccount component (src/components/superAdmin/superAdminAccount/superAdminAccount.module.scss), as they're already applied in the pagination component (src/components/pagination/pagination.module.scss) and they have no effect on layout.
> 2. If I'm right, these styles should not be applied in universityListPage component (src/pages/superAdminPages/universityListPage/universityListPage.module.scss), as they're already applied in the pagination component (src/components/pagination/pagination.module.scss) and they have no effect on layout.
> 3. Please, make the container a little bit smaller on these two pages, so it don't occupy the full width of page. Also, add margin or padding right under the pagination component on both pages.
> 
> 
> ![1](https://user-images.githubusercontent.com/71350925/121328765-4a236400-c91d-11eb-9807-74e439625d64.png)
> 2.
> ![2](https://user-images.githubusercontent.com/71350925/121328768-4abbfa80-c91d-11eb-9bdb-51897798caf9.png)

2021-06-10 14:28 UTC, TionCada approved these changes

2021-06-22 09:23 UTC, PashaZ approved these changes

2021-06-22 09:23 UTC, PashaZ commented
Well done

2021-06-23 08:31 UTC, Ihor-Kozachok approved these changes

2021-06-23 08:31 UTC, Igor-Kozachok commented on src/components/pagination/index.tsx
> +        onClick={() => {
потрібен тест на клік

2021-06-23 08:31 UTC, Igor-Kozachok commented on src/components/pagination/index.tsx
> +        onClick={() => {
Потрібен тест на клік

2021-06-23 09:22 UTC, ostannja commented on src/components/pagination/index.tsx
> +        onClick={() => {
The rows of the code in pagination.test.js, which are responsible for those clicks are ##114 155 163. So if to comment that rows the coverage of test decrease and the result is on the picture. 
![Знімок екрана 2021-06-23 121834](https://user-images.githubusercontent.com/54737176/123071307-3992e380-d41d-11eb-974e-1cedd1a8d0fe.png)
Cases are discribed if the currentPage is 2 or 3 with the number of total pages equal to 3

2021-06-28 08:57 UTC, merged