Logic #r141 add new specialty i kozachok
ita-social-projects/YIF_Frontend pull request #170
Opened 2021-06-04 09:47 UTC by Ihor-Kozachok

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-06-08 09:11 UTC, ostannja approved these changes
Great job!

2021-06-08 20:56 UTC, Dimundra requested changes

2021-06-08 20:56 UTC, Dimundra commented on src/components/superAdmin/addSpecialtyForm/addSpecialtyForm.module.scss
> +    .messagesContainer {
Definitely need to rewrite some styles, .topWrapper class cause error messages content to be unproperly located.

<img width="1920" alt="image_2021-06-08_17-30-05" src="https://user-images.githubusercontent.com/72043545/121206808-6ec9fe00-c881-11eb-81a9-90eae5e6ff06.png">

class that cause errors
<img width="1918" alt="image_2021-06-08_17-47-07" src="https://user-images.githubusercontent.com/72043545/121207057-a6d14100-c881-11eb-9ad9-a7af3ee7c7f8.png">

2021-06-08 20:56 UTC, Dimundra commented on src/components/superAdmin/addSpecialtyForm/addSpecialtyForm.module.scss
> +    .messagesContainer {
The accepted ui for error messages would be like this
![image](https://user-images.githubusercontent.com/72043545/121207350-e1d37480-c881-11eb-82ad-1f5133d0f98c.png)

2021-06-09 18:42 UTC, TionCada approved these changes

2021-06-09 20:22 UTC, Dimundra approved these changes

2021-06-09 20:23 UTC, merged