Feature fix style#55 Katya Nemerovetska
ita-social-projects/YIF_Frontend pull request #64
Opened 2021-01-17 21:16 UTC by Katy-dev

dev
## Click Up

## Summary of issue

fixed style for User option component
added some test to registrationPage

## Testing approach

jest

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=90%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-01-17 21:28 UTC, Rominos7 commented on src/components/forCabinetPage/userWorksSpace/userWorkSpace.module.scss
>    height: 50rem;
Shoud we change height from 50rem to 55 rem as well??

2021-01-17 21:34 UTC, andrew-melnychuk approved these changes, later dismissed
good

2021-01-17 22:15 UTC, Romanarkko approved these changes
Approve

2021-01-17 22:21 UTC, Romanarkko requested changes
Not approve, when i open image to change profile picture its shows wrong.

2021-01-18 07:43 UTC, Romanarkko approved these changes
Approve

2021-01-18 10:48 UTC, andrew-melnychuk approved these changes
good

2021-01-18 12:20 UTC, Rominos7 approved these changes
Good

2021-01-18 12:22 UTC, merged